sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "GIa+sbhjR+dfoNG2M7Ld8qnPVzJSflCtbK7I9JRrODXVR3jGPu2iAS3C0QiWANvw5Iz5GIUi6kaGG5SJj9IpmCpHLuRI5GzRRsm5bCwl6FqbdX2gOk6Zx7zPCRkDfA2Gt1UNmNXyOS8/HC7gHFlU3wqAltseyws9dtqBTKjLJzErcaCSgRW0loYmuKNpr/i9ARGvczMMwi6g2/UXWzgMGfhUlhPnuY9LtdJQnPr5SOt3zD7FklzSJjTMZXh+/BSli9cysvJCRCp4e/AjhJ9yH7RVxtwm8nQUsAG7On43ifncX6cTmVREkLV7ogURXspfqHDaYGV6Kp5eBLOzfE0pxeMzQldMpHaO1etLhwIJVhujmHr1Ok6En6YRSzzeRxBKumUE0N+1504KbZu/Tb5wfQKmvYzHqqKrp8zqbMXtFjfFqvL8lrTtzw/FvfdWiYsbAg9qvXmUzlMTF6LbS4rNx2Fml4k2njsF1UjO3TstJ+UbjTexgnUqupVXsP/NQk7h7Uk9FFuKaFMG3Mn/nN/zHWFzdWYO/OgyzU9rxFGUqDO6B1N8u9q2aDxiLyPGB5vEZ2D3AUBiP4u/Jy41EVtF/GTCMjA7J8ya60DdewA1xHPGJ/lEU97phih6Hc7RlP1k6JonOekd7JJGy6IaVfDT9+2sdRTgazg8tZ221s1fxaA="
  - secure: "Tbm3214irvdXBkWmMuHQ3KCSDLJeMUgGZ+WJMQ0cadN2At8E6+EeMLY7LcaEKctlEt3na9ay3zLBZhhrXc2713Ds1cRt0CIRlHVqVAjh/ytxTl9vYfIzvk9MDbwHPqJT3RdvkuBIX2hwrZzSFsyTrUdrScfy1OtI8sUU4EhVmo9yp2icpZ9KaunJPvRWmc9rh4mBuoe3sJQxXwiPfZ2jE/7xry+HE7nr/tDrH3h0ofx23mdfMtjynpjDP9Vi6eroNiyDsMVULJTtqL1QenlRF5D/ypfoOEuoJCbYUsOuIx12tQW2NdxconkYY/zxQIOfh2MdNRAOliZ3liRbw8dr3GGVJqSomPRz1PfKxsM7z/qmEErBgw5OabZcF284NRJElAhvYA1XbvxOFOGhXDFYe1hwvBwCG1aMxoi7vo0QfGH+tFLd0qWZucAlSkuOk4q2FVCuWNo49+EHedfsfgKr2xKsWw+PfsL7DLyo+DH2nOQi1NBfaceToULhhWRWyiteqH9HpMr6ZxuFIe27n6UNAhN09SFEQwKaDJH2Z8leokEnArrbQfYz0dnGLTbRp2JsNuZTH1T3dOpApbre0BJapTxGrl4U3GVZNqmeVuGugrWL9JUH7FxBICuFm4cb4W5K1V6KZQpT5SPEjd6BmRzRomRGSJdzT6QF93sR8K0ztVc="
  - secure: "dDOFQnhHX1hKEAys3Yuu8VU/NhskzfaYKRM/kuV4pc2HK/YzvehQYqp717fHGKU3bZ8P1wj89MUtnSkDAj9yeiCOto0uSkAOgZvNaNW/O97MP+beYpUUHaRt76Fyd4s+A3X7iiFTWgI5d+wJFw+aQm5xXGTxX1AUD1dIGQH1QCK3Hj39pVntN5nS15cDIau+pVmDJIe5B19VGpN98NPhal7d0VJZIlEEi4+LOUGnUdZ1ma/83Hh7rFUwq9ubtRzFxYA2QN5jZ9EwkoXHdpyhh6fLSpXmZAa2Q+Ur6YNQtaFq36+jqj4ANXcnr0HWWKY9LO+scB/jcPFwHZbPRgAsnuzVDhJL5BKs/uF4UyBWM/npKJB/Yu08geNNzyJHNgkkK4Sa+P7c8WzdfSl1LRHU7gW9pxZnJ2C7fVZmxd1DhdgpDpzBgHSP3GSJiWZbe9nQwSC0Y5E9ftobwhxbL6WrPb72/BxHhPskHuJDlRNwCt2FOBlJu7weXG+TWiEuvNmmAEM9Vc8hUwo5T9JD9OytLrmJCGxEO3/easHcmqKI1SP93Wz5XnspSCXi9bWDo/mpbndaFdJtrQb/sXAmzP9Ox71oRe0jOFB8famSXFxuQSh325ZqzYKainp7Vx3lrj3ktQTH0Yyy8NDFLqpXZw/0/m/dC/hvdxpSDdpThVasgWU="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
